apiVersion: v1
kind: Service
metadata:
  name: medicure-service
spec:
  type: NodePort
  selector:
    app: front-end
  ports:
    - protocol: TCP
      port: 8082
      targetPort: http-web-app-01
      